{% set name = "heaptrack" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KDE/heaptrack/archive/v{{ version }}.tar.gz
  sha256: 44e6aefc13460556acced7192bf3600605cd7a5f3a46e670c3127aeae97e19dd
  folder: source
  patches:
    - stdc_format.patch

build:
  number: 1
  skip: true  # [not linux]
  ignore_run_exports:
    - elfutils


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - libboost-devel
    - libunwind
    - elfutils
    - zlib
  run:
    - libunwind
    - elfutils

test:
  commands:
    - heaptrack_print --help

about:
  home: https://github.com/KDE/heaptrack
  license: GPL-2.0-or-later
  license_file: source/LICENSES/GPL-2.0-or-later.txt
  summary: 'heaptrack - a heap memory profiler for Linux'
  description: |
    Heaptrack traces all memory allocations and annotates these events with stack traces. Dedicated analysis tools then allow you to interpret the heap memory profile to:
      find hotspots that need to be optimized to reduce the memory footprint of your application
      find memory leaks, i.e. locations that allocate memory which is never deallocated
      find allocation hotspots, i.e. code locations that trigger a lot of memory allocation calls
      find temporary allocations, which are allocations that are directly followed by their deallocation
  doc_url: https://userbase.kde.org/Heaptrack
  dev_url: https://github.com/KDE/heaptrack

extra:
  recipe-maintainers:
    - bcouturi
    - chrisburr
